import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/requests'

const Home: NextPage = (props: any) => {
  const { results } = props
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header/>
      {/* Nav */}
      <Nav/>
      {/* Results */}
      <Results results={results}/>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const genre: string | string[] | undefined = context.query.genre
  console.log(genre)
  // @ts-ignore
  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`).then(res => res.json())
  return {
    props: {
      results: request.results,
    }
  }
}

export default Home
